<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(VftTargetFramework)</TargetFramework>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64;linux-x64;linux-arm64</RuntimeIdentifiers>
    <RootNamespace>VRCFaceTracking.ModuleProcess</RootNamespace>
    <SelfContained>true</SelfContained>
    <AppxBundlePlatforms Condition="'$(OS)' == 'Windows_NT'">x86|x64</AppxBundlePlatforms>
    <ApplicationManifest Condition="'$(OS)' == 'Windows_NT'">app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup Condition="'$(OS)' == 'Windows_NT'">
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VRCFaceTracking.Core\VRCFaceTracking.Core.csproj" />
    <ProjectReference Include="..\VRCFaceTracking.SDK\VRCFaceTracking.SDK.csproj" />
  </ItemGroup>
  <!-- Copy to Windows project on Windows builds only -->
  <Target Name="CopyExecutable" AfterTargets="Build" Condition="'$(OS)' == 'Windows_NT'">
    <Copy SourceFiles="$(OutputPath)VRCFaceTracking.ModuleProcess.exe" DestinationFolder="..\VRCFaceTracking\" SkipUnchangedFiles="true" />
  </Target>
</Project>